title: Ana Matić Škorić
logo: <img src="/ana2.jpg" alt="Profile Photo" style="width:250px; height:250px; border-radius:50%; object-fit:cover; display:block; margin-left:auto; margin-right:auto;">
location: Zagreb, Croatia and Philadelphia, USA
#uri: [linkedin](www.linkedin.com/in/ana-matić-škorić-3b260795) 
#show_downloads: false
#theme: jekyll-theme-minimal 
remote_theme: pmarsceill/just-the-docs
include: [_navigation.yml]
